import Head from 'next/head';
import Navigation from '../components/Navigation';
import Container from 'react-bootstrap/Container';
import Carousel from 'react-bootstrap/Carousel';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Card from 'react-bootstrap/Card';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Navigation />
			<Head>
				<title>NEXT INIT</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='bg'>
				<div className='dark-bg'>
					<Container fluid>
						<h5>
							Мастерская <br /> художественной ковки
						</h5>
						<h1>Кентавр</h1>
						<h7>Эксклюзивные кованые изделия ручной работы на заказ</h7>
						<Container className='benefits'>
							<Row className='justify-content-md-center'>
								<Col xs lg='2'>
									<img src='/5.png' />
									<br />
									Собственное Производство
								</Col>
								<Col md='auto'>
									<img src='/6.png' />
									<br />
									Изготовление по <br />
									проектам заказчика
								</Col>
								<Col xs lg='2'>
									<img src='/7.png' />
									<br />
									Более 20 лет
									<br /> успешной работы
								</Col>
							</Row>
						</Container>
					</Container>
				</div>
			</div>
			<Container>
				<Carousel>
					<Carousel.Item>
						<img className='d-block w-100' src='/9.jpg' alt='First slide' />
						<Carousel.Caption>
							<h3>Бесплатная доставка</h3>
							<p>Бесплатно доставляем и выгружаем ваш заказ.</p>
						</Carousel.Caption>
					</Carousel.Item>

					<Carousel.Item>
						<img className='d-block w-100' src='/9.jpg' alt='Second slide' />

						<Carousel.Caption>
							<h3>Бесплатная сборка</h3>
							<p>Собираем конструкцию на вашем участке.</p>
						</Carousel.Caption>
					</Carousel.Item>
					<Carousel.Item>
						<img className='d-block w-100' src='/9.jpg' alt='Third slide' />

						<Carousel.Caption>
							<h3>Бесплатный замер</h3>
							<p>Бесплатно замеряем размеры ващего участка.</p>
						</Carousel.Caption>
					</Carousel.Item>
				</Carousel>
			</Container>
			<Container>
				<Card>
					<Card.Body>
						<h1 className='text-center'>Примеры работ</h1>
					</Card.Body>
				</Card>

				<Row xs={1} md={2} className='g-4'>
					<Col>
						<Card>
							<Card.Img variant='top' src='/15.jpg' />
							<Card.Body>
								<Card.Title className='text-center'>Перила</Card.Title>
							</Card.Body>
						</Card>
					</Col>
					<Col>
						<Card>
							<Card.Img variant='top' src='/16.jpg' />
							<Card.Body>
								<Card.Title className='text-center'>Ворота</Card.Title>
							</Card.Body>
						</Card>
					</Col>
					<Col>
						<Card>
							<Card.Img variant='top' src='/13.jpg' />
							<Card.Body>
								<Card.Title className='text-center'>Лавки</Card.Title>
							</Card.Body>
						</Card>
					</Col>
					<Col>
						<Card>
							<Card.Img variant='top' src='/14.jpg' />
							<Card.Body>
								<Card.Title className='text-center'>Мосты</Card.Title>
							</Card.Body>
						</Card>
					</Col>
				</Row>
			</Container>
			<footer>
				<Link href='tel:+89100000000'>
					<a className='tel'>
						<img src='8.png' />
						+7 910 000 00 00
					</a>
				</Link>
			</footer>
		</>
	);
}
