import Head from 'next/head';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import Container from 'react-bootstrap/Container';
import Carousel from 'react-bootstrap/Carousel';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Card from 'react-bootstrap/Card';
import Link from 'next/link';
import Image from 'react-bootstrap/Image';

export default function Home() {
	return (
		<>
			<Navigation />
			<Head>
				<title>Blacksmith</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='bg'>
				<div className='dark-bg'>
					<Container fluid>
						<h5>
							Мастерская <br /> художественной ковки
						</h5>
						<h1>Кентавр</h1>
						<h5>Эксклюзивные кованые изделия ручной работы на заказ</h5>
						<Container className='benefits'>
							<Row className='justify-content-md-center'>
								<Col xs lg='2'>
									<Image className='icon' src='/icon1.png' />
									<br />
									Собственное Производство
								</Col>
								<Col md='auto'>
									<Image className='icon' src='/icon2.png' />
									<br />
									Изготовление по <br />
									проектам заказчика
								</Col>
								<Col xs lg='2'>
									<Image className='icon' src='/icon3.png' />
									<br />
									Более 20 лет
									<br /> успешной работы
								</Col>
							</Row>
						</Container>
					</Container>
				</div>
			</div>
			<Container>
				<Carousel>
					<Carousel.Item>
						<Image
							className='d-block w-100'
							src='/carusel.jpg'
							alt='First slide'
						/>
						<Carousel.Caption>
							<h3>Бесплатная доставка</h3>
							<p>Бесплатно доставляем и выгружаем ваш заказ.</p>
						</Carousel.Caption>
					</Carousel.Item>

					<Carousel.Item>
						<Image
							className='d-block w-100'
							src='/carusel.jpg'
							alt='Second slide'
						/>

						<Carousel.Caption>
							<h3>Бесплатная сборка</h3>
							<p>Собираем конструкцию на вашем участке.</p>
						</Carousel.Caption>
					</Carousel.Item>
					<Carousel.Item>
						<Image
							className='d-block w-100'
							src='/carusel.jpg'
							alt='Third slide'
						/>

						<Carousel.Caption>
							<h3>Бесплатный замер</h3>
							<p>Бесплатно замеряем размеры ващего участка.</p>
						</Carousel.Caption>
					</Carousel.Item>
				</Carousel>
			</Container>
			<Container>
				<Card>
					<Card.Body>
						<h1 className='text-center'>Примеры работ</h1>
					</Card.Body>
				</Card>

				<Row xs={1} md={2} className='g-4'>
					<Col>
						<Link href='/perila' passHref>
							<Card className='category'>
								<Card.Img variant='top' src='/perila.jpg' />
								<Card.Body>
									<Card.Title className='text-center'>Перила</Card.Title>
								</Card.Body>
							</Card>
						</Link>
					</Col>
					<Col>
						<Link href='/vorota' passHref>
							<Card className='category'>
								<Card.Img variant='top' src='/vorota.jpg' />
								<Card.Body>
									<Card.Title className='text-center'>Ворота</Card.Title>
								</Card.Body>
							</Card>
						</Link>
					</Col>
					<Col>
						<Link href='/lavki' passHref>
							<Card className='category'>
								<Card.Img variant='top' src='/lavki.jpg' />
								<Card.Body>
									<Card.Title className='text-center'>Лавки</Card.Title>
								</Card.Body>
							</Card>
						</Link>
					</Col>
					<Col>
						<Link href='/mosti' passHref>
							<Card className='category'>
								<Card.Img variant='top' src='/mosti.jpg' />
								<Card.Body>
									<Card.Title className='text-center'>Мосты</Card.Title>
								</Card.Body>
							</Card>
						</Link>
					</Col>
				</Row>
			</Container>
			<Footer />
		</>
	);
}
